In [ ]:
#10 de Marzo del 2026
import pandas as pd
import numpy as np
from numpy import random

In [ ]:
#Tipos de array de un elemento
array_0 = np.array(5)
print(array_0)

5


In [ ]:
#Arreglo de una dimension
array_1 = np.array([1,2,3,4,5,6])
print(array_1)

[1 2 3 4 5 6]


In [ ]:
#Arreglo de dos dimensiones
array_2 = np.array([[1,2,3],[4,5,6]])
print(array_2)

[[1 2 3]
 [4 5 6]]


In [ ]:
from numpy._core.multiarray import array
#Arreglo de 3 dimensiones
array_3 =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#Acceder a un elemento del arreglo de n dimensiones
#Index de los arrays
print(array_1[0])

1


In [ ]:
#Acceder a un elemento del arreglo de 2 dimensiones
#Seleccionamos la fila o columna 0, del elemento 1
print(array_2[0][1])

2


In [ ]:
print(array_2[1][1])

5


In [ ]:
#dimension, fila, columna, posicion
print(array_3[0][1][1])
#dimension, fila, columna, posicion
print(array_3[1][0][0])

5
7


In [ ]:
#Metodo Shape: Forma en la que esta compuesta la matriz o arreglo
print(array_1.shape)
print(array_2.shape)
print(array_3.shape)

(6,)
(2, 3)
(2, 2, 3)


In [ ]:
#Reestructuracion de arrays
#Reshape
print(array_1.reshape(1,6))
print(array_2.reshape(3,2))
print(array_3.reshape(2,3,2))

[[1 2 3 4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#Concatenacion: Union de arrays
print(np.concatenate((array_1,array_1)))
#Separacion de los elementos
print(np.array_split(array_1,2))
print(np.array_split(array_1,3))
#Ctrl k + ctrl c copiar todo el codigo

[110 101 186 166 190 126 129 163 154 180 110 101 186 166 190 126 129 163
 154 180]
[array([110, 101, 186, 166, 190]), array([126, 129, 163, 154, 180])]
[array([110, 101, 186, 166]), array([190, 126, 129]), array([163, 154, 180])]


In [ ]:
#Where
print(np.where(array_1==3))
#ordenar los datos del arreglo
array_N = np.array([10,50,2,0,7,6])
print(np.sort(array_N))

(array([2]),)
[ 0  2  6  7 10 50]


In [ ]:
#Ordenaer de manera descendente
print(np.sort(array_N)[::-1])

[50 10  7  6  2  0]


In [ ]:
#random
numero = random.randint(100,200,1) #(inicio,fin, num elementos)
print(numero)
#Generar matrices de numeros aleatorios
numero = random.randint(10, size=(5))
print(numero)

[172]
[7 4 2 8 7]


In [ ]:
#Generar matrices de 2 filas de 3 valores
numero = random.randint(10, size=(2,3))
print(numero)

[[4 7 5]
 [2 5 4]]


In [ ]:
#numeros decimales
numero = random.rand()
print(numero)

0.27961239727290155


In [ ]:
#Redondear decimales
numero = random.rand()
print(round(numero,2))

numero2 = random.rand() + 5
print(numero2)

numero3= random.rand(3,5)
print(numero3)

0.76
5.612846624107763
[[0.49949018 0.11216922 0.25357133 0.75227689 0.34088279]
 [0.49994213 0.21242788 0.26797463 0.44413056 0.66396918]
 [0.02943079 0.72375252 0.72868894 0.75990928 0.05036688]]


In [ ]:
#Listas
lista_nombres = ["Juan", "Pedro", "Maria"]
print(random.choice(lista_nombres))

Pedro


Ejercicios Numpy

Crea un array de 10 números aleatorios enteros entre 0 y 100.


In [ ]:
numero = random.randint(100, size=(10))
print(numero)

[ 5 38 25 22 39 22 48 43 44 47]


Crea un array de 5 números aleatorios decimales entre 0 y 1.


In [ ]:
numero = random.rand(1,5)
print(numero)

[[0.93579678 0.96555319 0.17061757 0.01354037 0.39250157]]


Crea dos arrays de números aleatorios enteros de longitud 5 y concaténalos.


In [ ]:
array_1 = random.randint(100,200,5)
array_2 = random.randint(100,200,5)
print(np.concatenate((array_1,array_2)))

[108 191 130 176 102 162 180 165 146 108]


Crea un array de 10 números aleatorios enteros y sepáralo en dos arrays de 5 elementos cada uno.


In [ ]:
array_1 = random.randint(100,200,10)
print(np.array_split(array_1,2))

[array([119, 147, 176, 102, 100]), array([100, 197, 177, 140, 111])]


Crea una matriz de 3x3 con números aleatorios decimales entre 0 y 1.


In [ ]:
#Generar matrices de 3 filas de 3 valores
numero = random.rand(3,3)
print(numero)

[[0.11671423 0.34945367 0.44056138]
 [0.37468346 0.11221332 0.05276852]
 [0.64370054 0.57933855 0.46940308]]


Crea un array de 10 números aleatorios enteros y selecciona 3 elementos al azar.


In [ ]:
array_1 = random.randint(10)
print(random.choice(array_1,3))

[6 6 7]


Crea un array de 10 números aleatorios enteros entre 0 y 100 y calcula la media.

In [ ]:
#Crea un array de 10 números aleatorios enteros entre 0 y 100 y calcula la media.
array_1 = random.randint(0,100,10)
media = np.mean(array_1)
print(media)
print(array_1)


42.4
[ 5 53 24  1 93 45 42 42 29 90]
