In [9]:
import numpy as np

arr1 = np.random.uniform(low=2, high=5, size=(5,5))
arr2 = np.random.rand(5,5)

print("Hola")
print(arr1)
print("--Arreglo 2--")
print(arr2)

vecX = []
vecY = []
vec_suma = []

for i in range(1):
    vecX.append(arr1[i])
    vecY.append(arr2[1])
    
print("--Vector X--")
print(vecX)
print("--Vector Y--")
print(vecY)
print("--Suma--")
for i in range(1):
    vec_suma.append(vecX[i] + vecY[i])
print(vec_suma)

Hola
[[2.32462966 3.82333697 3.48630922 3.91788959 3.38762441]
 [4.1732364  2.54228048 3.66673738 4.77635833 4.19864245]
 [4.84842651 2.27270164 2.76911072 3.60511246 4.8260982 ]
 [2.52676079 3.92412126 3.86479763 2.90284321 3.27611379]
 [2.61674802 4.22381509 3.10196376 3.83576267 4.24410911]]
--Arreglo 2--
[[0.73920652 0.26446007 0.44253444 0.83979471 0.65985475]
 [0.70122201 0.81241397 0.31386943 0.07730086 0.9863089 ]
 [0.80046309 0.34561803 0.66977798 0.08054443 0.38275898]
 [0.07282609 0.38729024 0.21515499 0.37725827 0.54638881]
 [0.58233799 0.87179002 0.65788676 0.50660017 0.60386361]]
--Vector X--
[array([2.32462966, 3.82333697, 3.48630922, 3.91788959, 3.38762441])]
--Vector Y--
[array([0.70122201, 0.81241397, 0.31386943, 0.07730086, 0.9863089 ])]
--Suma--
[array([3.02585168, 4.63575094, 3.80017864, 3.99519045, 4.3739333 ])]


### Ahora podemos tener una libreta local